version: '3.7'

services:

  mongodb:
    image: mongo
    volumes:
       - db-data:/data/db
    ports:
      - "27017:27017"
    networks: 
      - nw-pdv

  nginx1: 
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: gabrielltr/ngapi
    container_name: nginx1
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - nw-pdv
    depends_on:
      - "nodepdv"

  nodepdv:
    build:
      dockerfile: ./docker/pdv.dockerfile
      context: .
    image: gabrielltr/pdv
    container_name: nodepdv
    ports:
      - "3000"
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
    networks: 
      - nw-pdv
    depends_on:
      - "mongodb"

networks: 
  nw-pdv: 
    driver: bridge

volumes:
  db-data:

